[program]
changelog_user = EuroLinux Autopatch <devel@euro-linux.com>
package_config = False

[autodist]
enable_autodist = False

[re1]
match = (%%global pname python-%%{sname})
replace = \1
    
    %%global pgmajorversion 18
changelog = Add pgmajorversion global

[re2]
match = PGDG%%{\?dist}
replace = %%{?dist}
changelog = Remove PGDG release

[re3]
match = %%{\?dist}
replace = SM%%{?dist}
changelog = Add SM release

[re4]
match = export PATH=%%{pginstdir}/bin:\$PATH
replace = export PATH=%%{pginstdir}/bin:/usr/pgsql-%%{pgmajorversion}/bin:$PATH
changelog = Update PATH to include pgmajorversion bin directory

[re5]
match = (%%{__cp} -rp tests %%{buildroot}%%{python3_sitearch}/%%{sname}/tests)
replace = \1
    #Fix python shebang
    %%py3_shebang_fix %%{buildroot}%%{python3_sitearch}/%%{sname}/tests
changelog = Fix python shebang for tests